---
title: "Assignment_1"
output: html_document
---
```{r}
install.packages("rlist")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
sum_mults <-function(nums, n){

  total <- 0
  count <- 0
  if (n<0){
    return(0)
  }
 for(j in 1:n-1) {
   
  
  for (i in nums) {
    if (j%%i == 0) {
     total <- total + j
      count <- count + 1
      break
   }
   
    
  }
 }
  print(count)
  return(total)
 
}

sum_mults(c(3,5), 30)

```

```{r}
collatz_len <- function(n){
  count <- 1
  j <- vector()
  j <- c(j, n)
  while(n > 1){
    if(n%%2 == 0)
      n <- n/2
    else if(n %% 2 == 1)
      n <- 3*n +1
      
    count <- count + 1
    
    j <- c(j, n)
  }
  print(j)
  print(count)
  return(n)
  
  
}

collatz_len(17)
```



```{r}
reverse <- function(v){
  v <- sort(v, decreasing = TRUE)
  print(v)
  
}  



reverse(c(7,8,9))
reverse(c())
```
  

```{r}
drop <- function(v, n){
  count <- 1 
  for (i in v) {
    if(count == n){
     
      v <- v[-(i)]
      
      count <- 1
      
    }
    count <- count + 1
  }
  
  return(v)
}


drop(c(1,2,3,4,5), 2)
drop(c() , 4)
```

```{r}
intersect_3 <- function(v, w, x){
  temp <- vector()
  for (i in v) {
    #print(v[i])
    if ((v[i] %in% w) && (v[i] %in% x)) {
    # print(v[i])
      if(!(v[i] %in% temp))
        temp <- c(temp, v[i])
    }
    
    #
  }
  return(temp)
}
intersect_3(c(1,2,3,1) , c(1,1,3,2) , c(3,1,9,1))
```

```{r}
filter_vec <- function(v,p){
  temp <- vector()
  for (i in v){
    if(p(v[i])){
      temp <- c(temp, v[i])
      
    }
    
  }
 if(length(temp) > 0)
   print(temp)
  else
   print(NULL)
}  

p <- function(x){return(x>3)}
l <- 1:6
o <- 1:3
m <- filter_vec(o, p)

```

```{r}
n_fibs <- function(n){
  result <- vector()
  for (i in 1:n) {
    
    if(i == 1){
      result <- c(result, 1)
    }
    if(i == 2){
      result <- c(result, 1)
    }
    else
      result <- c(result, (result[i-1] + result[i-2]))
    
  }
  
 return(result)
  
}
n_fibs(2)
n_fibs(10)
```


```{r}
shift <- function(v,n){
  n <- n %% length(v)
  if(n == 0){
    return(l)
  }
  if(n == 1){
    n=3
  }
  else if(n == 3){
    n=1
  }
  l <- c(v[(n+1):length(v)], v[1:n])


  return(l)
}

shift(c(1,2,3,4), -2)


```

```{r}
rem_consec_dups <- function(v)
{
  length <- length(v)
  i <- 1
  while(i <= length)
  {
    if ((i-1)>=1) 
    {
      if (v[i] == v[i-1]) {
         v <- v[-(i)]
         length <- length - 1
         i <- 1
      }
    }
    i <- i+1
  }
  return(v)
}

rem_consec_dups(c(1,1,1,2,3,3,1,2,2))


```

```{r}
library(rlist)
n_even_fibs <- function(n){
  result <- list()
  i <- 1
  fib <- n_fibs(1000)
  for (i in 1:length(fib)) {
    if(length(result) < n){
      if ((fib[i] %% 2) == 0) {
        temp <- paste(toString(i), " : num ", toString(fib[i]), sep="", collapse=NULL)
       result <- append(result, temp)
      }
    }
  }
 return(result)
}

n_even_fibs(400)

```



